notifications:
  email:
    on_success: change
    on_failure: change

language: haskell
ghc:
- 7.4

# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
env:
 - RESOLVER=lts-3
 - RESOLVER=nightly
 - RESOLVER=ghc-7.8.4

sudo: false

install:
  - wget https://www.stackage.org/stack/linux-x86_64
  - tar -zxvf linux-x86_64
  - mv `ls | grep stack` stack
  - export PATH=`pwd`/stack:$PATH
  - stack --version 
  - stack setup --resolver $RESOLVER
  - stack build --resolver $RESOLVER

cache:
  directories:
    - $HOME/.stack

# Here starts the actual work to be performed for the package under test; any
# command which exits with a non-zero exit code causes the build to fail.
script:
  - echo "This will either error or succeed, we're just testing the build"
