notifications:
  email:
    on_success: change
    on_failure: change

language: haskell
ghc:
- 7.8
- '7.10'

# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
env:
 - USE_LTS_HASKELL=lts
 - NOSNAPSHOT=true

sudo: false

install:
 - travis_retry cabal update
 - if [[ `git log --format=%B -n 1 $TRAVIS_COMMIT` == *\[deps\]* ]]; then rm -rf ~/sandbox$USE_LTS_HASKELL; fi
 - mkdir -p ~/sandbox$USE_LTS_HASKELL
 - if [[ `ghc --numeric-version` == 7.8.* ]]; then
     STACKAGESNAPSHOT=;
   fi
 - if [[ `ghc --numeric-version` == 7.4.* ]]; then
     export PATH=$HOME/sandbox$USE_LTS_HASKELL/bin:$PATH;
     wget http://downloads.haskell.org/~ghc/7.10.2/ghc-7.10.2-x86_64-unknown-linux-deb7.tar.xz;
     tar -xJvf ghc-7.10.2-x86_64-unknown-linux-deb7.tar.xz;
     cd ghc-7.10.2;
     ./configure --prefix=$HOME/sandbox$USE_LTS_HASKELL;
     make install;
     cabal install cabal-install;
     cp ~/.cabal/bin/cabal $HOME/sandbox$USE_LTS_HASKELL/bin/;
     ghc-pkg init;
     cabal update;
     cd ..;
   fi
 - if [[ `ghc --numeric-version` == 7.10.* ]]; then STACKAGESNAPSHOT=lts-3;fi
 - if [[ -n "$NOSNAPSHOT" ]]; then STACKAGESNAPSHOT=; fi
 - if [[ -n "$STACKAGESNAPSHOT" ]]; then curl -L --silent https://www.stackage.org/$STACKAGESNAPSHOT/cabal.config | grep -v 'dixi ==' > cabal.config; fi
 - cd ~/sandbox$USE_LTS_HASKELL
 - cabal sandbox init
 - cd -
 - cp ~/sandbox$USE_LTS_HASKELL/cabal.sandbox.config .
 - cabal install -j2 --only-dependencies --enable-tests --enable-benchmarks

cache:
  directories:
    - $HOME/sandbox$USE_LTS_HASKELL

# Here starts the actual work to be performed for the package under test; any
# command which exits with a non-zero exit code causes the build to fail.
script:
 - if [[ `ghc --numeric-version` == 7.4.* ]]; then
     export PATH=$HOME/sandbox$USE_LTS_HASKELL/bin:$PATH; fi
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal check
 - cabal sdist
